name: Github Pages

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check internal links
        id: lychee-interal
        uses: lycheeverse/lychee-action@v2
        with:
          args: --config ./.config/lychee-internal.toml './book/**/*.md'
          fail: true

      - name: Check external links
        id: lychee-external
        uses: lycheeverse/lychee-action@v2
        with:
          args: --index-files README.md --config ./.config/lychee-external.toml './book/**/*.md'
          fail: true
        continue-on-error: true

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Build book
        run: mdbook build book

      - name: Publish book
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/book
